import { Video } from './types'
import { getGoogleDriveThumbnail } from './video-upload'

export const mockVideos: Video[] = [
    {
      id: "1",
      title: "#1 Adi",
      description: "",
      google_drive_id: "13ApBzZgehRRwQJwn-2SElbcXc-cz3uUC",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-15T10:30:00Z",
      updated_at: "2024-01-15T10:30:00Z",
      video_url: "https://drive.google.com/file/d/13ApBzZgehRRwQJwn-2SElbcXc-cz3uUC/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/13ApBzZgehRRwQJwn-2SElbcXc-cz3uUC/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "2",
      title: "#2 Adrian",
      description: "",
      google_drive_id: "1N2qCiiJ3O8n5F5R3xm9OVDLCAbZ1B7DF",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-16T14:20:00Z",
      updated_at: "2024-01-16T14:20:00Z",
      video_url: "https://drive.google.com/file/d/1N2qCiiJ3O8n5F5R3xm9OVDLCAbZ1B7DF/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1N2qCiiJ3O8n5F5R3xm9OVDLCAbZ1B7DF/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "3",
      title: "#3 Bärenboys",
      description: "",
      google_drive_id: "1cc5AXVGORhOpcuboh5Qk3ynzyKzvMQYu",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-17T09:15:00Z",
      updated_at: "2024-01-17T09:15:00Z",
      video_url: "https://drive.google.com/file/d/1cc5AXVGORhOpcuboh5Qk3ynzyKzvMQYu/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1cc5AXVGORhOpcuboh5Qk3ynzyKzvMQYu/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "4",
      title: "#4 Cedric",
      description: "",
      google_drive_id: "1qHcQWtIeghkZrUrxRl8Ahdcr2hVZW4X9",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-18T11:45:00Z",
      updated_at: "2024-01-18T11:45:00Z",
      video_url: "https://drive.google.com/file/d/1qHcQWtIeghkZrUrxRl8Ahdcr2hVZW4X9/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1qHcQWtIeghkZrUrxRl8Ahdcr2hVZW4X9/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "5",
      title: "#5 Emil",
      description: "",
      google_drive_id: "1y67cwM629jV1RiS1V_3wQtkbECChf_0h",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-19T16:30:00Z",
      updated_at: "2024-01-19T16:30:00Z",
      video_url: "https://drive.google.com/file/d/1y67cwM629jV1RiS1V_3wQtkbECChf_0h/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1y67cwM629jV1RiS1V_3wQtkbECChf_0h/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "6",
      title: "#6 Franz",
      description: "",
      google_drive_id: "1OWkgwbHZPy-YJwkmKdgPlbPI0OCXbpwj",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-20T08:00:00Z",
      updated_at: "2024-01-20T08:00:00Z",
      video_url: "https://drive.google.com/file/d/1OWkgwbHZPy-YJwkmKdgPlbPI0OCXbpwj/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1OWkgwbHZPy-YJwkmKdgPlbPI0OCXbpwj/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "7",
      title: "#7 Georg",
      description: "",
      google_drive_id: "18oUyFk1njdpFzxxSD_qRx9ELlGH_WmVp",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-21T12:15:00Z",
      updated_at: "2024-01-21T12:15:00Z",
      video_url: "https://drive.google.com/file/d/18oUyFk1njdpFzxxSD_qRx9ELlGH_WmVp/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/18oUyFk1njdpFzxxSD_qRx9ELlGH_WmVp/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "8",
      title: "#8 Jarno",
      description: "",
      google_drive_id: "1MNNf4vEc72MMqtcwJXYUaDUFaWVzRNhi",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-22T14:45:00Z",
      updated_at: "2024-01-22T14:45:00Z",
      video_url: "https://drive.google.com/file/d/1MNNf4vEc72MMqtcwJXYUaDUFaWVzRNhi/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1MNNf4vEc72MMqtcwJXYUaDUFaWVzRNhi/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "9",
      title: "#9 Justus",
      description: "",
      google_drive_id: "1Fj0JrJtiAmjtOKwovR1MBsJN02bxZb-y",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-23T10:30:00Z",
      updated_at: "2024-01-23T10:30:00Z",
      video_url: "https://drive.google.com/file/d/1Fj0JrJtiAmjtOKwovR1MBsJN02bxZb-y/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1Fj0JrJtiAmjtOKwovR1MBsJN02bxZb-y/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "10",
      title: "#10 Justus",
      description: "",
      google_drive_id: "1LuCtaC6vCPmc0vHWhxpr5SPatM6s-U8E",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-24T13:20:00Z",
      updated_at: "2024-01-24T13:20:00Z",
      video_url: "https://drive.google.com/file/d/1LuCtaC6vCPmc0vHWhxpr5SPatM6s-U8E/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1LuCtaC6vCPmc0vHWhxpr5SPatM6s-U8E/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "11",
      title: "#11 Mailo",
      description: "",
      google_drive_id: "1J8gXw7F0hVvAlr5bpmuFl8gPKzcC-wjy",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-25T09:10:00Z",
      updated_at: "2024-01-25T09:10:00Z",
      video_url: "https://drive.google.com/file/d/1J8gXw7F0hVvAlr5bpmuFl8gPKzcC-wjy/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1J8gXw7F0hVvAlr5bpmuFl8gPKzcC-wjy/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "12",
      title: "#12 Leon",
      description: "",
      google_drive_id: "1WL4NIFl5Q64Wefba7sOFV9zlejoBNM6v",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-26T15:40:00Z",
      updated_at: "2024-01-26T15:40:00Z",
      video_url: "https://drive.google.com/file/d/1WL4NIFl5Q64Wefba7sOFV9zlejoBNM6v/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1WL4NIFl5Q64Wefba7sOFV9zlejoBNM6v/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "13",
      title: "#13 Lina",
      description: "",
      google_drive_id: "1dYcwb496pcNpCRmjmwIdHX9hlwZ6pXox",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-27T11:25:00Z",
      updated_at: "2024-01-27T11:25:00Z",
      video_url: "https://drive.google.com/file/d/1dYcwb496pcNpCRmjmwIdHX9hlwZ6pXox/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1dYcwb496pcNpCRmjmwIdHX9hlwZ6pXox/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "14",
      title: "#14 Luca",
      description: "",
      google_drive_id: "1MJIMO5Pdt8-3tbE7IUnpnJC3WwLp1lm2",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-28T16:50:00Z",
      updated_at: "2024-01-28T16:50:00Z",
      video_url: "https://drive.google.com/file/d/1MJIMO5Pdt8-3tbE7IUnpnJC3WwLp1lm2/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1MJIMO5Pdt8-3tbE7IUnpnJC3WwLp1lm2/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "15",
      title: "#15 Luca",
      description: "",
      google_drive_id: "1nTtmjUZEynCzrjPwniYo_rhaOG0A0JXy",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-29T08:35:00Z",
      updated_at: "2024-01-29T08:35:00Z",
      video_url: "https://drive.google.com/file/d/1nTtmjUZEynCzrjPwniYo_rhaOG0A0JXy/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1nTtmjUZEynCzrjPwniYo_rhaOG0A0JXy/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "16",
      title: "#16 Lucas",
      description: "",
      google_drive_id: "1KoVkK838iVIwKEX_I9I3pNLsvHVLuQzu",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-30T12:10:00Z",
      updated_at: "2024-01-30T12:10:00Z",
      video_url: "https://drive.google.com/file/d/1KoVkK838iVIwKEX_I9I3pNLsvHVLuQzu/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1KoVkK838iVIwKEX_I9I3pNLsvHVLuQzu/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "17",
      title: "#17 Lukas",
      description: "",
      google_drive_id: "1Hx5oXjWKZOsjjAAM_Dqo4F6nNqguaWo9",
      status: "ready",
      vote_count: 0,
      created_at: "2024-01-31T14:55:00Z",
      updated_at: "2024-01-31T14:55:00Z",
      video_url: "https://drive.google.com/file/d/1Hx5oXjWKZOsjjAAM_Dqo4F6nNqguaWo9/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1Hx5oXjWKZOsjjAAM_Dqo4F6nNqguaWo9/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "18",
      title: "#18 Martin",
      description: "",
      google_drive_id: "1gvA4eehTL2QpX22mS7ALVpjiUU_0nda6",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-01T10:20:00Z",
      updated_at: "2024-02-01T10:20:00Z",
      video_url: "https://drive.google.com/file/d/1gvA4eehTL2QpX22mS7ALVpjiUU_0nda6/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1gvA4eehTL2QpX22mS7ALVpjiUU_0nda6/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "19",
      title: "#19 Mattheo",
      description: "",
      google_drive_id: "1GPUVVp-uMJMHxQYXSi21q8NjXcxKnnMf",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-02T13:45:00Z",
      updated_at: "2024-02-02T13:45:00Z",
      video_url: "https://drive.google.com/file/d/1GPUVVp-uMJMHxQYXSi21q8NjXcxKnnMf/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1GPUVVp-uMJMHxQYXSi21q8NjXcxKnnMf/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "20",
      title: "#20 Maxi",
      description: "",
      google_drive_id: "1EVywIUtoFDToVlc_nEzdSgfRCj8xPkpg",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-03T09:30:00Z",
      updated_at: "2024-02-03T09:30:00Z",
      video_url: "https://drive.google.com/file/d/1EVywIUtoFDToVlc_nEzdSgfRCj8xPkpg/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1EVywIUtoFDToVlc_nEzdSgfRCj8xPkpg/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "21",
      title: "#21 Maximilian",
      description: "",
      google_drive_id: "1irYhm0oLOqYwRmSbhWwX_xy8AUsYpxl8",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-04T15:15:00Z",
      updated_at: "2024-02-04T15:15:00Z",
      video_url: "https://drive.google.com/file/d/1RrFcpArWrx3oRQXpI3idMseW_AD-qir6/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1RrFcpArWrx3oRQXpI3idMseW_AD-qir6/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "22",
      title: "#22 Mika",
      description: "",
      google_drive_id: "1_FMzUtr83p6ayt_aEGLgjpP28JwD4jRv",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-05T11:40:00Z",
      updated_at: "2024-02-05T11:40:00Z",
      video_url: "https://drive.google.com/file/d/1_FMzUtr83p6ayt_aEGLgjpP28JwD4jRv/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1_FMzUtr83p6ayt_aEGLgjpP28JwD4jRv/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "23",
      title: "#23 Niklas",
      description: "",
      google_drive_id: "1V1WbtfdLI8uf-6-7Himv8LSedoMBLZHy",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-06T16:25:00Z",
      updated_at: "2024-02-06T16:25:00Z",
      video_url: "https://drive.google.com/file/d/1V1WbtfdLI8uf-6-7Himv8LSedoMBLZHy/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1V1WbtfdLI8uf-6-7Himv8LSedoMBLZHy/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "24",
      title: "#24 Noah",
      description: "",
      google_drive_id: "1YQ7n0NlZeXNVhUnVqtP4u_ttk74z2dOk",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-07T08:50:00Z",
      updated_at: "2024-02-07T08:50:00Z",
      video_url: "https://drive.google.com/file/d/1YQ7n0NlZeXNVhUnVqtP4u_ttk74z2dOk/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1YQ7n0NlZeXNVhUnVqtP4u_ttk74z2dOk/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "25",
      title: "#25 Riccardo",
      description: "",
      google_drive_id: "1KZQWstKWe9U85vIThq0ZxlZcS0B_M9He",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-08T12:35:00Z",
      updated_at: "2024-02-08T12:35:00Z",
      video_url: "https://drive.google.com/file/d/1KZQWstKWe9U85vIThq0ZxlZcS0B_M9He/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1KZQWstKWe9U85vIThq0ZxlZcS0B_M9He/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "26",
      title: "#26 Sandro",
      description: "",
      google_drive_id: "1ANzbL25UHyF5qGwj0Kjz2hulqxdy8DUO",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-09T14:20:00Z",
      updated_at: "2024-02-09T14:20:00Z",
      video_url: "https://drive.google.com/file/d/1ANzbL25UHyF5qGwj0Kjz2hulqxdy8DUO/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1ANzbL25UHyF5qGwj0Kjz2hulqxdy8DUO/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "27",
      title: "#27 Tom",
      description: "",
      google_drive_id: "1V3xoYcMOYSWCsEwh6n8pSbgXxivJC337",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-10T10:05:00Z",
      updated_at: "2024-02-10T10:05:00Z",
      video_url: "https://drive.google.com/file/d/1V3xoYcMOYSWCsEwh6n8pSbgXxivJC337/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1V3xoYcMOYSWCsEwh6n8pSbgXxivJC337/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "28",
      title: "#28 Yann",
      description: "",
      google_drive_id: "17rI5Ru8LQIPAe3pSAkJILTjm4wT_qKTm",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-11T13:30:00Z",
      updated_at: "2024-02-11T13:30:00Z",
      video_url: "https://drive.google.com/file/d/17rI5Ru8LQIPAe3pSAkJILTjm4wT_qKTm/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/17rI5Ru8LQIPAe3pSAkJILTjm4wT_qKTm/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "29",
      title: "#29 Leopold",
      description: "",
      google_drive_id: "1GnLYyJL7qQHtY_Vr0FyU5knmfY9kh0EI",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-12T15:45:00Z",
      updated_at: "2024-02-12T15:45:00Z",
      video_url: "https://drive.google.com/file/d/1GnLYyJL7qQHtY_Vr0FyU5knmfY9kh0EI/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/1GnLYyJL7qQHtY_Vr0FyU5knmfY9kh0EI/view?usp=sharing"),
      user_has_voted: false,
    },
    {
      id: "30",
      title: "#30 Leander",
      description: "",
      google_drive_id: "19XKBAs7PDyxb1bcVV6ycYVJvlyqn1FDM",
      status: "ready",
      vote_count: 0,
      created_at: "2024-02-13T09:20:00Z",
      updated_at: "2024-02-13T09:20:00Z",
      video_url: "https://drive.google.com/file/d/19XKBAs7PDyxb1bcVV6ycYVJvlyqn1FDM/view?usp=sharing",
      thumbnail_url: getGoogleDriveThumbnail("https://drive.google.com/file/d/19XKBAs7PDyxb1bcVV6ycYVJvlyqn1FDM/view?usp=sharing"),
      user_has_voted: false,
    },
  ];
